name: 'Jira Release Action'
description: 'Creates a release in Jira for a version'
author: 'velith'
inputs:
  jira_project_key:
    description: 'Project key for the Jira project'
    required: true
  jira_version:
    descritpion: 'Version name to release in Jira'
    required: true
  jira_hostname:
    description: 'Hostname for the Jira server'
    required: true
  jira_release_version:
    description: 'Optional name for the version to change before release'
    required: false
  jira_transition_id:
    description: 'Optionally transition Jira ticket in release to this transition id'
    required: false
  jira_status_name:
    description: 'Transitions issues that have this Jira status (only required if transition id provided)'
    required: false
runs:
  using: 'docker'
  image: 'docker://ghcr.io/velith/jira-release-action:v0.2.2'